### PR TITLE
Bugfixes2

### PR DESCRIPTION
**Pull request by vinipsmaker**
Continued from https://github.com/maidsafe/rust-utp/pull/14

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/rust-utp/16)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @canndrew

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by vinipsmaker** [comment]
The only test that still needs some work before I merge this PR is `socket::test::test_receive_unexpected_reply_type_on_connect`. The failure happens because the test expects to see a `ErrorKind::ConnectionRefused`, but receives a `"Connection timed out"`. It doesn't seem difficult to fix this one, but I'll only continue to work on it on Monday.

**Comment by vinipsmaker** [comment]
> The only test that still needs some work before I merge this PR is `socket::test::test_receive_unexpected_reply_type_on_connect`. The failure happens because the test expects to see a `ErrorKind::ConnectionRefused`, but receives a `"Connection timed out"`. It doesn't seem difficult to fix this one, but I'll only continue to work on it on Monday.

I found out the code that caused the regression is: https://github.com/maidsafe/rust-utp/commit/fd77155261c57e4c12aa991ed920d873b162ccaa#diff-31f30e4109441593ec66bc2db678a87aR336

I won't revert the commit that introduced the regression because it fixes an important bug that wasn't tested. Peter found a lot of issues when he started emulating dropped packets and writing more-than-just-unit-tests (something in the direction of integration tests). Something that was seemingly being neglected previously.

I could **very very easily** add code to make the test pass, but the current behaviour looks more right to me than the test described behaviour. Therefore, I'll change the test (not something new by now).

**Comment by vinipsmaker** [comment]
> The only test that still needs some work before I merge this PR is `socket::test::test_receive_unexpected_reply_type_on_connect`. The failure happens because the test expects to see a `ErrorKind::ConnectionRefused`, but receives a `"Connection timed out"`. It doesn't seem difficult to fix this one, but I'll only continue to work on it on Monday.

I found out the code that caused the regression is: https://github.com/maidsafe/rust-utp/commit/fd77155261c57e4c12aa991ed920d873b162ccaa#diff-31f30e4109441593ec66bc2db678a87aR336

I won't revert the commit that introduced the regression because it fixes an important bug that wasn't tested. Peter found a lot of issues when he started emulating dropped packets and writing more-than-just-unit-tests (something in the direction of integration tests). Something that was seemingly being neglected previously.

I could **very very easily** add code to make the test pass, but the current behaviour looks more right to me than the test described behaviour. Therefore, I'll change the test (not something new by now).

**Comment by vinipsmaker** [comment]
All tests pass now. Code can be merged safely.

**Pull request merged**
