### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by inetic**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/rust-utp/14)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @canndrew

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by vinipsmaker** [comment]
I hope this will be merged soon.

**Comment by dirvine** [comment]
If you are happy with it then please do, I checked it earlier and looks good to me.

**Comment by dirvine** [comment]
Ah just noticed it is now conflicting :-(

**Comment by vinipsmaker** [comment]
> Ah just noticed it is now conflicting :-(

Is it? I see the "Merge pull request" button okay.

**Comment by dirvine** [comment]
Sorry I got mixed up with another PR, please go ahead :-)

**Comment by vinipsmaker** [comment]
Rest of PR seems okay.

**Comment by dirvine** [comment]
Nice catch, happy investigating there man. Can you update with your findings please.

**Comment by vinipsmaker** [comment]
> Nice catch, happy investigating there man. Can you update with your findings please.

Of course.

Gonna flood you guys here just like I was trying to flood [at some other place](https://github.com/maidsafe/crust/pull/454).

**Comment by dirvine** [comment]
:D flooding with info is good, worry not :-)

**Comment by vinipsmaker** [comment]
I'm still gluing everything together to verify this finally stabilizes rust-utp.

**Comment by vinipsmaker** [comment]
> I'm still gluing everything together to verify this finally stabilizes rust-utp.

Glue time is over and this is one of the two last PRs that I need to merge to get rust-utp in good shape.

> Can you update with your findings please.

https://github.com/maidsafe/crust/pull/454#issuecomment-173417793

Better to subscribe to this other PR too if you want to check all information.

**Comment by vinipsmaker** [comment]
I got an unexpected failure while I was hoping to only get a failure for other tests: https://gist.github.com/vinipsmaker/ec469ed9c23fb71b34a9

It's not that bad, as it's very rare (good for users, bad for devs that will have a much more difficult time tracking the failure down). Unpatched rust-utp is far worse and this patchset really makes several improvements. I'll investigate this unexpected failure later (maybe after the merge, as there's really no need to wait that much longer after to merge some code that we know improve the library).

Also, I'll be continuing work on this other PR: https://github.com/maidsafe/rust-utp/pull/16

**Pull request closed without merging**
